# Generated by Django 5.1.2 on 2024-10-22 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('secteur_activite', models.CharField(max_length=300)),
                ('email_contact', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=200)),
                ('filiere', models.CharField(max_length=200)),
                ('cv', models.FileField(upload_to='media/cv')),
                ('candidatures_etat', models.CharField(choices=[('EN ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_stage', models.CharField(choices=[('TEMPS PLEIN', 'Temps plein'), ('PARTIEL', 'partiel')], max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('duree', models.IntegerField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('date_limite_postulation', models.DateField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.servicestage')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('EN ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], max_length=200)),
                ('date_reponse', models.DateField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.offrestage')),
            ],
        ),
        migrations.AddField(
            model_name='entreprise',
            name='offres_publiees',
            field=models.ManyToManyField(blank=True, to='gestion.servicestage'),
        ),
    ]
