# Generated by Django 5.1.2 on 2024-10-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='offres_publiees',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='candidatures_etat',
        ),
        migrations.RemoveField(
            model_name='servicestage',
            name='nom',
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='cv',
            field=models.FileField(blank=True, upload_to='media/cv'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='offrestage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicestage',
            name='responsable',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
